name: run-ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build
        run: docker build -t edn-dev .
        env:
          DOCKER_BUILDKIT: 1
      - name: Test
        run: docker run -t edn-dev
