name: run-ci
run-name: ${{ github.actor }} is running ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - run: docker build -t edn-dev .
      - run: docker run -t edn-dev
