name: run-ci
run-name: ${{ github.actor }} is running ci
on:
  pull-request:
    branches:
      - main
      - dev

jobs:
  build:
    name: build
    run: docker build -t edn-dev .
  test:
    name: test
    run: docker run -t edn-dev
