name: run-ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - run: docker build -t edn-dev .
      - run: docker run -t edn-dev
